# Generated by Django 5.1.4 on 2025-01-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('niños', 'Niños'), ('jovenes', 'Jóvenes'), ('adultos', 'Adultos')], max_length=50)),
                ('capacidad_por_turno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('ocupada', 'Ocupada'), ('liberada', 'Liberada'), ('terminada', 'Terminada')], default='reservada', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuarios.perfilcliente')),
                ('pista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.pista')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
                'unique_together': {('pista', 'fecha', 'hora')},
            },
        ),
    ]
